import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://i.etsystatic.com/17708073/r/il/b5dfda/2790668258/il_794xN.2790668258_skpf.jpg",
    title: "Flat Plain Gold Bracelet",
    star: <AiFillStar className="rating-star text-yellow-400" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Jewelry by ARSA",
    color: "gold",
    category: "Gold",
  },
  {
    img: "https://m.media-amazon.com/images/I/41pH+33tP+L.jpg",
    title: "Stianless Steel Gold Plated love Bracelet",
    star: <AiFillStar className=" text-yellow-400" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Glamlife Anti Tarnish Bangles",
    color: "gold",
    category: "Gold",
  },

  {
    img: "https://m.media-amazon.com/images/I/41CJGakkGBL.jpg",
    title: "Cuff Nail Design Bracelet",
    star: <AiFillStar className=" text-yellow-400" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Glamlife Anti Tarnish Bangles",
    color: "gold",
    category: "Gold",
  },
  {
    img: "https://m.media-amazon.com/images/I/51IuI8kLsXL._UL1024_.jpg",
    title: "Gold Bracelet",
    star: <AiFillStar className=" text-yellow-400" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Melorra",
    color: "black",
    category: "Gold",
  },
  {
    img: "https://m.media-amazon.com/images/I/61O1Rqdd1zL._UL1500_.jpg",
    title: "Sterling Silver Classy Link Bracelet",
    star: <AiFillStar className=" text-yellow-400" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "GIVA",
    color: "silver",
    category: "diamond",
  },
  {
    img: "https://m.media-amazon.com/images/I/31Of6W8OP1L.jpg",
    title:
      "Silver Adjustable Tennis Cubic Zirconium AD American diamond Bracelet",
    star: <AiFillStar className=" text-yellow-400" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "NANDANA COLLECTIONS",
    color: "silver",
    category: "diamond",
  },

  {
    img: "https://m.media-amazon.com/images/I/61JMHC8AbuL._UL1440_.jpg",
    title: "American diamond Studded Bracelet",
    star: <AiFillStar className=" text-yellow-400" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "YouBella",
    color: "silver",
    category: "diamond",
  },

  {
    img: "https://m.media-amazon.com/images/I/91Phj9+PcfL._UL1500_.jpg",
    title: "Gold Plated American Charming Golden Bracelets",
    star: <AiFillStar className=" text-yellow-400" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "349",
    company: "Fashion Frill",
    color: "gold",
    category: "Gold",
  },

  {
    img: "https://m.media-amazon.com/images/I/61JNAzCKcdL._UL1000_.jpg",
    title: "Crystal Multilayer 3-5 pcs Set Charm Bracelets ",
    star: <AiFillStar className=" text-yellow-400" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Shining Diva Fashion",
    color: "gold",
    category: "Gold",
  },

  {
    img: "https://m.media-amazon.com/images/I/615aBmc7emL._UL1500_.jpg",
    title: "Shimmering Green Cubic Zirconia & Pearls Contemporary Style Kada",
    star: <AiFillStar className=" text-yellow-400" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "ZAVERI PEARLS ",
    color: "green",
    category: "Gold",
  },
  {
    img: "https://m.media-amazon.com/images/I/610ZB3VQf1L._UL1497_.jpg",
    title: "'Perception' Bracelet",
    star: <AiFillStar className=" text-yellow-400" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Estele",
    color: "red",
    category: "Gold",
  },
  {
    img: "https://m.media-amazon.com/images/I/616yV7LD3bL._UL1500_.jpg",
    title: "Sterling Silver Tennis Bracelet",
    star: <AiFillStar className=" text-yellow-400" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "AZURFA",
    color: "black",
    category: "Gold",
  },
  {
    img: "https://m.media-amazon.com/images/I/71xjuehNT8L._UL1500_.jpg",
    title: "Classy Gold & White Pearl Beaded Cuff Bracelets",
    star: <AiFillStar className=" text-yellow-400" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "452",
    company: "ToniQ",
    color: "white",
    category: "Gold",
  },
  {
    img: "https://m.media-amazon.com/images/I/71nz0sF6b4L._UL1208_.jpg",
    title: " Rose Gold Crystal Charm Bracelet ",
    star: <AiFillStar className=" text-yellow-400" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "GGB",
    color: "black",
    category: "Gold",
  },

  {
    img: "https://m.media-amazon.com/images/I/61Zrm9cS1JL._UL1500_.jpg",
    title: " Green Stones Embellished Elephant Drop Ethnic Bracelet",
    star: <AiFillStar className=" text-yellow-400" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "390",
    company: "ZAVERI PEARLS",
    color: "green",
    category: "Gold",
  },
  {
    img: "https://m.media-amazon.com/images/I/71Gqg4QSONL._UL1500_.jpg",
    title: "Rhodium Plated Bracelet",
    star: <AiFillStar className=" text-yellow-400" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "ZENEME",
    color: "silver",
    category: "diamond",
  },
  {
    img: "https://m.media-amazon.com/images/I/51TSb1w+nRL._UL1500_.jpg",
    title: "7 Chakra Bracelet",
    star: <AiFillStar className=" text-yellow-400" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "CraftVatika",
    color: "white",
    category: "titanium",
  },
  {
    img: "https://m.media-amazon.com/images/I/61CpMky5H8L._UL1001_.jpg",
    title: "Retro Bicycle Chain Personality Wild Bracelet",
    star: <AiFillStar className=" text-yellow-400" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "STARBRILLIANT",
    color: "blue",
    category: "titanium",
  },
  {
    img: "https://m.media-amazon.com/images/I/61SEWaqxcnL._UL1500_.jpg",
    title: "Bio Magnetic Super Light Weight Black Titanium Men's Bracelet",
    star: <AiFillStar className=" text-yellow-400" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Zivom®",
    color: "black",
    category: "titanium",
  },
  {
    img: "https://m.media-amazon.com/images/I/51donFF27lL._UL1000_.jpg",
    title: "Titanium Steel Vegan Leather Micro Insert Bracelet ",
    star: <AiFillStar className=" text-yellow-400" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Brizberry",
    color: "black",
    category: "leather",
  },
  {
    img: "https://m.media-amazon.com/images/I/51d+oj27vpL._UL1500_.jpg",
    title: "Casual Band Collection Strand Bracelet",
    star: <AiFillStar className=" text-yellow-400" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "280",
    company: "Yellow Chimes",
    color: "black",
    category: "leather",
  },
  {
    img: "https://m.media-amazon.com/images/I/618IFWLMkAL._UL1500_.jpg",
    title: "Two-Strand Red Braided Leather Bangle Bracelet ",
    star: <AiFillStar className=" text-yellow-400" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "COOL STEEL AND BEYOND",
    color: "red",
    category: "leather",
  },
  {
    img: "https://m.media-amazon.com/images/I/713L9iDzIFL._UL1500_.jpg",
    title: "Set of 7 Red and Gold Beaded Bracelets",
    star: <AiFillStar className=" text-yellow-400" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Blueberry",
    color: "red",
    category: "Gold",
  },

  {
    img: "https://m.media-amazon.com/images/I/51GghICKBqS._UL1100_.jpg",
    title: "Magnetic-Clasp Genuine Leather Wrap Bracelets",
    star: <AiFillStar className=" text-yellow-400" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "528",
    company: "Yellow Chimes",
    color: "black",
    category: "leather",
  },
  {
    img: "https://m.media-amazon.com/images/I/51i2CDQIeiL.jpg",
    title: "Vegan Leather Micro Insert Bracelet",
    star: <AiFillStar className=" text-yellow-400" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Brizberry",
    color: "black",
    category: "leather",
  },
  {
    img: "https://m.media-amazon.com/images/I/61ykFBwyMVL._UL1500_.jpg",
    title: "Triple-lap White Braided Leather Bracelet",
    star: <AiFillStar className=" text-yellow-400" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "COOL STEEL AND BEYOND",
    color: "white",
    category: "leather",
  },
  {
    img: "https://m.media-amazon.com/images/I/41mzKQnZW0L._UL1440_.jpg",
    title: "Black Bracelet for Men",
    star: <AiFillStar className=" text-yellow-400" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Police",
    color: "black",
    category: "leather",
  },
  {
    img: "https://m.media-amazon.com/images/I/71KW7GqrfaL._UY575_.jpg",
    title: "Austrian Diamonds Embellished Party Bling Cuff Bracelet",
    star: <AiFillStar className=" text-yellow-400" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "ZAVERI PEARLS",
    color: "gold",
    category: "diamond",
  },
];

export default data;